### ISSUE TITLE
Make it build with ghc-9.10

### ISSUE THREAD

**Issue by erikd** [wrengr/unix-bytestring#58]
Only needs a `base` dependency bump, so this can be done with a Hackage metadata edit.

**Comment by erikd** [comment]
As a Hackage Trustee I have editied the metadata on Hackage to bump the base dependency.

**Comment by erikd** [comment]
Would be happy to take over maintainer ship of this package if you would like to give it up.

**Comment by wrengr** [comment]
Fixed by https://github.com/wrengr/unix-bytestring/commit/0cb0d99b2ab048090b227867bfe77cae12eb027a

Sorry for being so out of touch the last few years; I'm finally in a position to become a more active maintainer again.
